#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

from modules.result_writer import update_results

def main():
    fib_seq = [1, 2]
    fib = 0
    while(fib < 4000000):
        fib = sum(fib_seq[-2:])
        fib_seq.append(fib)

    fib_even = filter(lambda x: x % 2 == 0, fib_seq)
    even_sum = sum(fib_even)

    update_results(even_sum, 2)

main()